Guild Missions v0.1.2
blish-hud/bhud-pkgs pull request #34
Opened 2021-07-29 14:53 UTC by EntRhoPi

Basic module that will help with guild missions. Currently providing a database for guild treks and their nearest waypoints.

2021-07-29 15:02 UTC, agaertner requested changes

2021-07-29 15:02 UTC, agaertner commented on manifests/entrhopi/Guild-Missions/0.1.2.json
> +  "namespace": "Guild_Missions",
Make sure to use a nickname of yours as a namespace prefix for your modules.

Eg. EnRhoPi.Guild_Missions

1. The prefix should be the same as the name of your module folder where the manifest lies in this repository.
2. Don't just edit the namespace in this manifest. Also add the prefix to files and project of the module itself.

This makes sure that there won't be any conflicts with other modules.

2021-07-29 15:45 UTC, EntRhoPi reviewed
Namespace is now fixed in manifest and project. New v0.1.2 is now available for download.

2021-08-04 19:02 UTC, dlamkins commented
Thanks for submitting your module!

2021-08-04 19:03 UTC, merged